### ISSUE TITLE
Does litep2p support connecting to nodes behind NAT networks?

### ISSUE THREAD

**Issue by Ma233** [paritytech/litep2p#108]
Hi, I found that the `dial` method of `WebRtcTransport` returns a `NotSupported` Error.
With my limited knowledge, it appears that only WebRTC offers a hole punching mechanism among all transport implementations. 
Does this imply that litep2p nodes are unable to connect to a node concealed in a NAT network?
When two nodes establish connection, is it essential to ensure that at least one of them has a public IP address?

**Comment by dmitry-markin** [comment]
Hi, `WebRTC` implementation in litep2p only supports WebRTC Direct connections (see [libp2p WebRTC spec](https://github.com/libp2p/specs/blob/master/webrtc/webrtc-direct.md) for details). This means litep2p can only act as a server for other nodes to connect to. The purpose of WebRTC support in litep2p is to allow JS nodes running in a browser to connect to litep2p nodes with routable public addresses without the need to setup trusted TLS certificates.
