### ISSUE TITLE
Make features optional

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/litep2p#161]
Right now due to str0m litep2p pulls OpenSSL, which is very undesirable due to how annoying it is to deal with.

Please consider making a set of optional features that selectively enable certain protocols. For example I'd like to disable WebRTC protocol because it is not used in Substrate anyway and makes me deal with OpenSSL with literally no benefit whatsoever. And annoyingly litep2p is a mandatory dependency of Substrate now, so I can't get rid of it easily either.

Something like libp2p-core and stuff would be much preferred over this monolith, but at very least having features that can be disabled would be very much appreciated.

**Comment by dmitry-markin** [comment]
This can be done, of course. However, one thing to consider is that WebRTC is going to be enabled by default in substrate as soon as this transport is stable in litep2p, as this is a long awaited feature needed by https://github.com/smol-dot/smoldot.

**Comment by nazar-pc** [comment]
RocksDB is also enabled by default, but it can be disabled by specifying `default-features = false`, so I hope the same could be done here as well. Most of Substrate seems to only need a few types, so support for specific transports can be made behind features.
