### ISSUE TITLE
kad: Implement `GET_PROVIDERS` command

### ISSUE THREAD

**Issue by lexnv** [paritytech/litep2p#167]
Implement the `GET_PROVIDERS` command:
- spec: https://github.com/libp2p/specs/tree/master/kad-dht#content-provider-discovery

This command is similar to `GET_VALUE`. One possible solution is to extend `GetRecordContext` to support two different messages:
 https://github.com/paritytech/litep2p/blob/a27d0072913be67cce904e2e8c465cc37ec5223a/src/protocol/libp2p/kademlia/query/get_record.rs#L83-L84
 
 
 https://github.com/paritytech/litep2p/blob/a27d0072913be67cce904e2e8c465cc37ec5223a/src/protocol/libp2p/kademlia/query/get_record.rs#L117-L118

**Comment by dmitry-markin** [comment]
Superseded by https://github.com/paritytech/litep2p/issues/201 & https://github.com/paritytech/litep2p/issues/202.
