### ISSUE TITLE
Implement connection limits

### ISSUE THREAD

**Issue by altonen** [paritytech/litep2p#17]
```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/litep2p/pull/185
- [ ] https://github.com/paritytech/litep2p/pull/194
```

**Comment by lexnv** [comment]
Monitoring a litep2p node with a libp2p node, it is clear that litep2p can sustain many more connections.

This data point supports the connection limits, as I believe it will free up some more resources (ie not having to deal with that many connections):


![Screenshot 2024-07-09 at 14 18 46](https://github.com/paritytech/litep2p/assets/60601340/5eb545aa-ff1b-4318-a08e-1252ab162261)

**Comment by altonen** [comment]
The connections also allocate quite a bit of memory, like ~600KB of memory per connection. Those numbers are configurable but it'd be better to have proper connection limits which could be as simple as just checking the total number of connections in `TransportManager` before accepting an inbound connection/starting to dial remote peer.

The more advanced option would be to not poll TCP/WebSocket listeners at all if the maximum number of connections has been reached but last time I looked into it, it required some non-trivial API rework in the transport interface.

If resource consumption is an issue, you can decrease the sizes of Noise read/write buffers in the transport configs.
