### ISSUE TITLE
identify: Update local node listen addresses

### ISSUE THREAD

**Issue by lexnv** [paritytech/litep2p#191]
The identify protocol provides as response a `listen_addresses` field.
The remote peer uses this field to insert self reported addresses into the Kademlia DHT.

Substrate makes use of the listen addresses [here](https://github.com/paritytech/polkadot-sdk/blob/00a5cb3a0b43492391141f0a98f5e1666ebfd3cf/substrate/client/network/src/litep2p/mod.rs#L916-L918).

The problem is that the identify protocol starts with a static set of addresses, which may expire or become invalid:

https://github.com/paritytech/litep2p/blob/2d1a4b48bb7f0f768b825ce88d456fe741c922df/src/protocol/libp2p/identify.rs#L272-L276

This might be one of the reasons why we've seen low connectivity with peers over the long term (~90 days).

The Identify protocol can be extended to receive verified addresses for healthier listen addresses.
For the Substrate perspective, when we deem a "remote address" as valid (after 2 encounters), that address needs to be reported back to the Identify protocol.
Libp2p already has a similar mechanism of discovery via the `ExternalAddressDiscovered` and confirming addresses.

**Comment by dmitry-markin** [comment]
Yeah, it shouldn't be like this. With libp2p backend `Identify` "listen addresses" field actually contains discovered external addresses, no matter when they were discovered.
