### ISSUE TITLE
Consider integrating substrate's `Peerset` into notification protocol implementation

### ISSUE THREAD

**Issue by dmitry-markin** [paritytech/litep2p#58]
Due to asynchronous nature of communication between `Peerset` in substrate's litep2p backend and notifications protocol implementation in litep2p, there are state consistency issues like described in this comment: https://github.com/paritytech/polkadot-sdk/blob/f212d54c2eb97879880cebde6516bc413e3764fc/substrate/client/network/src/litep2p/shim/notification/peerset.rs#L584-L596.

Specifically, the inbound substream can be seen as outbound from substrate's viewpoint if the nodes happen to open the substream in the same time. There are possibly other inconsistencies. (Note: the same applies to `ProtocolController` <-> `Notifications` in substrate).

The implementation of `Peerset` would be simpler if it was integrated with notification protocol in litep2p. Consider other pros and cons of this and, probably, move `Peerset` into litep2p notification protocol.

**Comment by altonen** [comment]
There's also this: https://github.com/paritytech/litep2p/issues/34

**Comment by dmitry-markin** [comment]
> There's also this: #34

Completely missed it. Closing this one.
